version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
    environment:
      - xpack.security.enabled=false
      #- xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms4096m -Xmx4096m
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    ports:
     - "9200:9200"
     - "9300:9300"
    networks:
      elk:
        aliases:
          - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    restart: always
    ports:
     - "5601:5601"
    networks:
      - elk
  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.1
    container_name: logstash
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx2048m -Xms2048m"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - elk

networks:
  elk:
volumes:
  esdata:
    driver: local
